server {
  listen 9090;
  listen [::]:9090;

  root /var/www;

  index index.html index.htm;

  location / {
    try_files $uri $uri/ /index.html;
    add_header Access-Control-Allow-Origin *;
  }

  location ~ /\.ht {
    deny all;
  }

}
